name: flutter_stripe
description: Flutter library for Stripe. Supports PaymentSheets, Apple & Google Pay, SCA, PSD2 and much more.
version: 1.0.2
homepage: https://github.com/flutter-stripe/flutter_stripe
repository: https://github.com/flutter-stripe/flutter_stripe

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  stripe_android:
    git:
      url: https://github.com/ibariens/flutter_stripe.git
      ref: main
      path: packages/stripe_android
  stripe_ios:
    git:
      url: https://github.com/ibariens/flutter_stripe.git
      ref: main
      path: packages/stripe_ios
  stripe_platform_interface:
    git:
      url: https://github.com/ibariens/flutter_stripe.git
      ref: main
      path: packages/stripe_platform_interface
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0




